name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 7
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '7'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Build with Maven and run tests
        run: mvn clean package

      - name: Extract project version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/spring-boot-react-ci-cd-aws-tf:latest -t ghcr.io/${{ github.repository_owner }}/my-java-app:${{ env.VERSION }} .

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/spring-boot-react-ci-cd-aws-tf:latest
          docker push ghcr.io/${{ github.repository_owner }}/spring-boot-react-ci-cd-aws-tf:${{ env.VERSION }}
